spring.application.name=book-my-show
spring.datasource.url=jdbc:postgresql://localhost:5432/BookMyshow
spring.datasource.username=postgres
spring.datasource.password=Bunny@9826
spring.jpa.hibernate.ddl-auto=update